server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdb
    username: user1
    password: user1!

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update  #create 프로젝트실행시 무조건 신규 생성, update 추 가
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #엔티티 생성시 변수명 그대로
      use-new-id-generator-mappings: false  #jpa 넘버링 전략 미준수
    show-sql: true
    properties:
      hibernate.format_sql: true   # 쿼리문 포맷
#      hibernate.dialect: org.hibernate.dialect.Oracle10gDialect

  jackson:
    serialization:
      fail-on-empty-beans: false


