-- PK 조회
/*
SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS T1
	     JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE T2
	          ON T1.TABLE_CATALOG = T2.TABLE_CATALOG
		          AND T1.TABLE_SCHEMA = T2.TABLE_SCHEMA
		          AND T1.TABLE_NAME = T2.TABLE_NAME
		          AND T1.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
where t1.CONSTRAINT_TYPE = 'PRIMARY KEY'
	and (T1.CONSTRAINT_SCHEMA , T1.TABLE_NAME) IN(
	SELECT SCHEMANAME, TABLENAME
	FROM PG_TABLES
	WHERE tablename not like '%prt_p%'
	GROUP BY SCHEMANAME, TABLENAME
);*/
-- UNIQUE 제약조건 추가
-- alter table PLAYER add CONSTRAINT PLAYER_UK1 UNIQUE (PLAYERNAME);


SELECT *
FROM PLAYER
;


SELECT
	*
FROM
	Player
WHERE
	Playername ='test'
	AND password = 'test';